### ISSUE TITLE
Upgrade latex on docs.iad1.psf.io

### ISSUE THREAD

**Issue by JulienPalard** [python/psf-salt#145]
I'm having build issues on docs.iad1.psf.io while french PDFs, but locals build are working. I spotted xelatex and babel are quite old on docs server:

For babel (in the texlive-latex-base package) I have `2018/05/02 3.20 The Babel package` while docs.iad1 have `2013/12/03 3.9h The Babel package`.

For XeTex:
- XeTeX 3.1415926-2.5-0.9999.3-2014012222 (TeX Live 2013/Debian) does not work
- XeTeX 2018.20180505-1 works
- XeTeX 2016.20170123-5 works
- XeTex 2014* not tested

If it's easy, maybe upgrading them would help.

**Comment by ewdurbin** [comment]
docs.iad1.psf.io is still Ubuntu 14.04, so we should be considering an upgrade in the near term (before April 2019).

In the meantime, if we can find a PPA providing a more up to date version it is straightforward.

**Comment by JulienPalard** [comment]
`mendex` 3.0 is not crashing, at least on my Debian, so the update would probably just fix this too.

**Comment by benjaminp** [comment]
I wonder if you can generate acceptable PDFs directly from HTML these days (epub?). It would be nice to drop the complex LaTeX toolchains.

**Comment by JulienPalard** [comment]
@benjaminp I really don't know, and not willing to dive into PDF generation at the moment þ
