### ISSUE TITLE
Automate addition of pypa/get-pip versions

### ISSUE THREAD

**Issue by ewdurbin** [python/psf-salt#185]
https://github.com/pypa/get-pip/issues/50 and similar come up when pypa/get-pip adds a new version. optimally the configurations for specific versions such as [symlinking](https://github.com/python/psf-salt/commit/d33fa8d044a9e080a36f645b8d83ec3eed799010#diff-0fa7d7354111196cd6e84aa1fdcc9328R103-R115) and [purging](https://github.com/python/psf-salt/commit/d33fa8d044a9e080a36f645b8d83ec3eed799010#diff-0fa7d7354111196cd6e84aa1fdcc9328R179-R185) should be automated.

**Comment by ewdurbin** [comment]
@pradyunsg I believe this is all handled via the work around https://github.com/python/psf-salt/pull/202, closing.

please re-open if it is still something we need to consider.

**Comment by pradyunsg** [comment]
Oh yea, I didn't even realise that we still had this open! This is definitely done. :)
