### ISSUE TITLE
@NatanBagrov ,

### ISSUE THREAD

**Issue by fig666** [python/psf-salt#231]
@NatanBagrov ,
 In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here.

__Originally posted by @tilakrayal in https://github.com/tensorflow/tensorflow/issues/55323#issuecomment-1075873318__

**Comment by NatanBagrov** [comment]
I assume this was opened by a mistake.

**Comment by fig666** [comment]
this was modified to help beta test but was input to hasty by emulated bot program
