### ISSUE TITLE
psfmember.org certificate renewal

### ISSUE THREAD

**Issue by JulienPalard** [python/psf-salt#239]
The psfmember.org certificate is about to expire (in 11 days from now), and it's not the first time it goes that far, what could we do to enhance the situation?

**Comment by JulienPalard** [comment]
psfmember.org certificates expires in 8 days.

**Comment by ewdurbin** [comment]
renewed.

**Comment by ewdurbin** [comment]
This host is being migrated in July to managed hosting. Due to the configuration of the current web host, LE issuance automation has been deemed low priority among other tasks. Thanks for being on top of monitoring endpoints <3
