### ISSUE TITLE
Need Fastly key setup for production www.python.org

### ISSUE THREAD

**Issue by frankwiles** [python/psf-salt#29]
Hey Everyone, 

We need to set the Fastly API Key so the app code can automatically PURGE when Pages and Downloads (and likely eventually other aspects of the site) are edited. 

So ultimately pydotorg.settings.server needs to contain: 

FASTLY_API_KEY = '<the secret key>'

This will likely need to be setup in Consul, so I wasn't sure exactly how to go about putting together a pull request for it.

**Comment by dstufft** [comment]
I just setup pillar data for the Fastly API key. You can use ``{{ pillar["fastly"]["api_key"] }}`` inside of a template to get the Fastly API key, and you need to add ``{dev,prod}.secrets.fastly`` to ``pillar/{dev,prod}/top.sls``.
