### ISSUE TITLE
Automate fetching lists of new Fastly IPs

### ISSUE THREAD

**Issue by ewdurbin** [python/psf-salt#291]
#290 updated the firewall for the cdn-logs host with the current ranges of Fastly IP addresses fetched via the API at https://developer.fastly.com/reference/api/utils/public-ip-list/

We should add a mechanism to automatically keep this list up to date so we don't cause logs to stop flowing again. Whatever range was being used to send syslog streams changed sometime in may and it was missed causing fastly to stop reporting any logs at all.

**Comment by egeakman** [comment]
@ewdurbin did you skip the letter "r" on purpose between "q" and "s" here: https://github.com/python/psf-salt/blob/d6c01b1241f402a6e202cc988b5aa5abf090c96a/pillar/base/firewall/fastly-logging.sls#L51-L56

**Comment by ewdurbin** [comment]
@egeakman good catch :) I manually typed... so I guess I just skipped r :)

**Comment by ewdurbin** [comment]
Resolved via #295
