### ISSUE TITLE
gzip off? 

### ISSUE THREAD

**Issue by frankwiles** [python/psf-salt#30]
Is there a reason I'm not thinking of that gzip is turned off? 

https://github.com/python/psf-salt/blob/master/salt/pydotorg/config/pydotorg.nginx.jinja#L264

This hurts site performance quite a bit, was wondering if it was there by mistake. 

```
psf-salt frank]$ curl -I -H 'Accept-Encoding: gzip,deflate' https://www.python.org/
HTTP/1.1 200 OK
Date: Mon, 12 Jan 2015 17:27:34 GMT
Server: nginx
Content-Type: text/html; charset=utf-8
X-Frame-Options: SAMEORIGIN
Content-Length: 46032
Accept-Ranges: bytes
Via: 1.1 varnish
Age: 2865
X-Served-By: cache-dfw1834-DFW
X-Cache: HIT
X-Cache-Hits: 33
Vary: Cookie
Public-Key-Pins: max-age=600; includeSubDomains; pin-sha256="WoiWRyIOVNa9ihaBciRSC7XHjliYS9VwUGOIud4PB18="; pin-sha256="5C8kvU039KouVrl52D0eZSGf4Onjo4Khs8tmyTlV3nU="; pin-sha256="5C8kvU039KouVrl52D0eZSGf4Onjo4Khs8tmyTlV3nU="; pin-sha256="lCppFqbkrlJ3EcVFAkeip0+44VaoJUymbnOaEUk7tEU="; pin-sha256="TUDnr0MEoJ3of7+YliBMBVFB4/gJsv5zO7IxD9+YoWI="; pin-sha256="x4QzPSC810K5/cMjb05Qm4k3Bw5zBn4lTdO/nEW/Td4=";
Strict-Transport-Security: max-age=63072000; includeSubDomains
```

gzip should take say the front page content down from 45K to 9K which is a big win on mobile, results will be even better/greater for things like the site CSS and JS.

**Comment by gutworth** [comment]
Maybe due to BREACH mitigation. @dstufft, you know? If so, maybe we should only turn off gzip when there's a 3-rd party referrer per https://community.qualys.com/blogs/securitylabs/2013/08/07/defending-against-the-breach-attack.

**Comment by dstufft** [comment]
BREACH mitigation is the only thing I can think of. It's super easy to turn it on for things like static files and the like since they will never have secret data in them. For the actual pages themselves I'm not sure of the state of the art in BREACH mitigation if there's a good way of actually handling that or not.

**Comment by frankwiles** [comment]
Yeah gzip even for just the static assets would be a big win on performance.

**Comment by dstufft** [comment]
It might be worth handling gzip on the Fastly side of things fwiw. I believe Fastly will only cache one object then and dynamically do the gziping for us instead of needing to cache 2 objects, one with compression and one without.

**Comment by frankwiles** [comment]
Yep that's what I was thinking too. I'm not super familiar with Fastly's interface, but I could take a stab at changing the config this weekend when traffic is lower.

**Comment by gutworth** [comment]
I enabled Fastly gzip on static mime types.

**Comment by frankwiles** [comment]
Hmmm I'm still seeing uncompressed css and in fact, it seems Fastly isn't caching these at all as it is always a miss.  Check out: 

curl -I https://www.python.org/ 
curl -I https://www.python.org/static/stylesheets/style.css
curl -I https://www.python.org/static/stylesheets/mq.css
curl -I https://www.python.org/static/js/libs/masonry.pkgd.min.js

**Comment by gutworth** [comment]
Curl doesn't send the `Accept-Encoding` header by default.
```
% curl -I -H 'Accept-Encoding: gzip,deflate' https://www.python.org/static/stylesheets/style.css
HTTP/1.1 200 OK
Server: nginx
Content-Type: text/css
Last-Modified: Thu, 16 Apr 2015 20:31:00 GMT
ETag: "55301c04-46683"
Cache-Control: max-age=604800, public
X-Clacks-Overhead: GNU Terry Pratchett
Content-Encoding: gzip
Content-Length: 110709
Accept-Ranges: bytes
Date: Sat, 02 May 2015 16:25:26 GMT
Via: 1.1 varnish
Age: 53490
Connection: keep-alive
X-Served-By: cache-atl6226-ATL
X-Cache: HIT
X-Cache-Hits: 14
Vary: Accept-Encoding
Public-Key-Pins: max-age=600; includeSubDomains; pin-sha256="WoiWRyIOVNa9ihaBciRSC7XHjliYS9VwUGOIud4PB18="; pin-sha256="5C8kvU039KouVrl52D0eZSGf4Onjo4Khs8tmyTlV3nU="; pin-sha256="5C8kvU039KouVrl52D0eZSGf4Onjo4Khs8tmyTlV3nU="; pin-sha256="lCppFqbkrlJ3EcVFAkeip0+44VaoJUymbnOaEUk7tEU="; pin-sha256="TUDnr0MEoJ3of7+YliBMBVFB4/gJsv5zO7IxD9+YoWI="; pin-sha256="x4QzPSC810K5/cMjb05Qm4k3Bw5zBn4lTdO/nEW/Td4=";
Strict-Transport-Security: max-age=63072000; includeSubDomains
```

**Comment by gutworth** [comment]
Better yet, just look in browser devtools.

**Comment by frankwiles** [comment]
Yep you're right, for some reason I always forget curl doesn't send that header.  YSlow was showing them as not gzipped as well, but it does seem it's working fine.  Thanks!
