### ISSUE TITLE
Another staging?

### ISSUE THREAD

**Issue by frankwiles** [python/psf-salt#43]
Hi Guys, 

There is some considerable work being done on reworking the navigation on python.org.  It'll likely be a multi-week iterative process so I'd rather not use the existing staging for this in case there are other hot issues to be worked in between. 

Would it be possible to setup staging2 or something on the same hardware as staging? Just a separate venv, DB, and branch to use?

**Comment by gutworth** [comment]
That shouldn't be too hard.

**Comment by gutworth** [comment]
There's now https://staging2.python.org/. It has a copy of the staging database. It's currently using the master branch. Tell me what you want it to be.

**Comment by frankwiles** [comment]
Awesome thanks for getting this done so quickly.  Submitted a PR to change the branch to 'staging2' https://github.com/python/psf-salt/pull/44 thanks!
