### ISSUE TITLE
Docs(migration guide): File transfer instructions fail due to missing keys

### ISSUE THREAD

**Issue by JacobCoffee** [python/psf-salt#436]
The [migration docs](https://infra.psf.io/guides/migration-recipe.html#stop-services-on-old-host) mention:

> 
> If the service has pillar data for backups (see pillar/prod/backup/$service.sls), run rsync once to move the bulk of data and as necessary to watch for changes:
> 
> sudo -E -s rsync -av --rsync-path="sudo rsync" username@hostname:/pathname/ /pathname/

However this fails on all user accounts I tried `ee, coffee` because of missing keys.
I would think it intentional that we do not want inter-service SSH capabilities, but the docs need some sort of update on this.

It is also not feasible to transfer 100s of GB worth of data from `prod host` -> `local pc` -> `new host`

**Comment by JacobCoffee** [comment]
Maybe this is a limitation of my yubikey usage, but also generating a key, adding to authorized_keys on the prod host, etc. isnt great either.

**Comment by ewdurbin** [comment]
A few lines up in the docs there it notes SSH AgentForwarding via `-A`, which is why this failed.

Perhaps a slightly more obvious admonition would help "Ensure your session has AgentFowrwarding or ssh-config includes it for the hosts".
