### ISSUE TITLE
HTTP rate limiting

### ISSUE THREAD

**Issue by ewdurbin** [python/psf-salt#502]
We currently have a couple services that ostensibly have HTTP rate limiting configured, but it is not clear that it is functioning as expected. Namely [bugs/roundup](https://github.com/python/psf-salt/blob/375e1e95e48fb35a615806e5a86926cb7f6c4584/salt/bugs/config/nginx.conf.jinja#L6) which is a pretty consistent noisy service due to crawlers/traffic.

Let's assess the current state of rate limiting for services managed by our salt infrastructure and being served by our haproxy load balancers (it should be all of them?) to determine the functionality of rate limiting and if there's some way we could consolidate that rate limiting into the haproxy layer rather than having it be service by service.
```[tasklist]
### Tasks
- [x] Assess missing, if any, loadbalanced services
- [ ] Investigage doing rate limiting with haproxy
```

**Comment by JacobCoffee** [comment]
I think this is the list of items not behind (most/all are expected I think?)

- backups
- consul
- cdn-logs
- mail
- Mailman3
- Pythontest
